# Generated by Django 5.0.1 on 2024-08-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuserapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='maior_idade',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
